// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class CriminalCaseReportFormPost
    {

        [JsonProperty("office")]
        public string Office { get; set; }

        [JsonProperty("case_type")]
        public string CaseType { get; set; }

        [JsonProperty("case_flags")]
        public string CaseFlags { get; set; }

        [JsonProperty("citation")]
        public string Citation { get; set; }

        [JsonProperty("pending_citations")]
        public string PendingCitations { get; set; }

        [JsonProperty("filed_from ")]
        public string FiledFrom { get; set; }

        [JsonProperty("filed_to ")]
        public string FiledTo { get; set; }

        [JsonProperty("terminal_digit")]
        public string TerminalDigit { get; set; }

        [JsonProperty("pending_defendants")]
        public string PendingDefendants { get; set; }

        [JsonProperty("fugitive_defendants")]
        public string FugitiveDefendants { get; set; }

        [JsonProperty("nonfugitive_defendants")]
        public string NonfugitiveDefendants { get; set; }

        [JsonProperty("sort1")]
        public string Sort1 { get; set; }

        [JsonProperty("sort2")]
        public string Sort2 { get; set; }

        [JsonProperty("sort3")]
        public string Sort3 { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("CGIPerl")]
        public string CGIPerl { get; set; }
    }

}
