// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class AliasTable
    {

        [JsonProperty("partyName")]
        public string PartyName { get; set; }

        [JsonProperty("partyType")]
        public string PartyType { get; set; }

        [JsonProperty("dba")]
        public string Dba { get; set; }

        [JsonProperty("dbaBusinessName")]
        public string DbaBusinessName { get; set; }
    }

}
