// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class CalendarEventTable
    {

        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("subevents")]
        public Subevent[] Subevents { get; set; }
    }

}
