// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class CaseAlias
    {

        [JsonProperty("header1")]
        public Header Header1 { get; set; }

        [JsonProperty("aliasTable")]
        public AliasTable[] AliasTable { get; set; }

        [JsonProperty("billing")]
        public Billing Billing { get; set; }

        [JsonProperty("parsed")]
        public bool Parsed { get; set; }
    }

}
