// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class CategoryEvent
    {

        [JsonProperty("Category")]
        public string Category { get; set; }

        [JsonProperty("Event")]
        public string Event { get; set; }

        [JsonProperty("DocumentURL")]
        public string DocumentURL { get; set; }

        [JsonProperty("DocumentURLName")]
        public string DocumentURLName { get; set; }
    }

}
