// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class CrCasesTable2
    {

        [JsonProperty("CaseNumberTitle")]
        public string CaseNumberTitle { get; set; }

        [JsonProperty("CaseDates")]
        public string CaseDates { get; set; }

        [JsonProperty("DaysPending")]
        public string DaysPending { get; set; }

        [JsonProperty("Notes")]
        public string Notes { get; set; }
    }

}
