// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class CriminalCaseReport
    {

        [JsonProperty("USCourt")]
        public string USCourt { get; set; }

        [JsonProperty("USCourtBranch")]
        public string USCourtBranch { get; set; }

        [JsonProperty("CaseTitle")]
        public string CaseTitle { get; set; }

        [JsonProperty("numberOfCasesReported")]
        public string NumberOfCasesReported { get; set; }

        [JsonProperty("crCasesTable2")]
        public CrCasesTable2[] CrCasesTable2 { get; set; }

        [JsonProperty("crCasesTable")]
        public CrCasesTable[] CrCasesTable { get; set; }

        [JsonProperty("crCasesSummaryTable")]
        public CrCasesSummaryTable[] CrCasesSummaryTable { get; set; }

        [JsonProperty("billing")]
        public Billing Billing { get; set; }

        [JsonProperty("sidebar")]
        public string Sidebar { get; set; }

        [JsonProperty("parsed")]
        public bool Parsed { get; set; }
    }

}
