// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class DeadlinesHearingsSelectOptionValues
    {

        [JsonProperty("sort1")]
        public string[][] Sort1 { get; set; }

        [JsonProperty("sort2")]
        public string[][] Sort2 { get; set; }

        [JsonProperty("sort3")]
        public string[][] Sort3 { get; set; }
    }

}
