// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class Doc
    {

        [JsonProperty("URL")]
        public string URL { get; set; }

        [JsonProperty("URLName")]
        public string URLName { get; set; }
    }

}
