// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class DocketActivityReportSummaryTable
    {

        [JsonProperty("Casenumber")]
        public string Casenumber { get; set; }

        [JsonProperty("All")]
        public string All { get; set; }
    }

}
