// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class DocketActivityReport2
    {

        [JsonProperty("CaseNumberTitle")]
        public object CaseNumberTitle { get; set; }

        [JsonProperty("Dates")]
        public Dates Dates { get; set; }

        [JsonProperty("CategoryEvent")]
        public CategoryEvent CategoryEvent { get; set; }

        [JsonProperty("Docketedby")]
        public Docketedby Docketedby { get; set; }

        [JsonProperty("Notes")]
        public object Notes { get; set; }
    }

}
