// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class Eventlist
    {

        [JsonProperty("dockReportURI")]
        public string DockReportURI { get; set; }

        [JsonProperty("docketReportURIName")]
        public string DocketReportURIName { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("plaintiff")]
        public string Plaintiff { get; set; }

        [JsonProperty("defendant")]
        public string Defendant { get; set; }

        [JsonProperty("calEventsURI")]
        public string CalEventsURI { get; set; }

        [JsonProperty("textOrder")]
        public string TextOrder { get; set; }
    }

}
