// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class JudgementIndexTables
    {

        [JsonProperty("CaseNumberTitle")]
        public object CaseNumberTitle { get; set; }

        [JsonProperty("JudgmentDescription")]
        public JudgmentDescription JudgmentDescription { get; set; }

        [JsonProperty("Status")]
        public string Status { get; set; }
    }

}
