// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class JudgementIndexReport
    {

        [JsonProperty("USCourt")]
        public string USCourt { get; set; }

        [JsonProperty("USCourtBranch")]
        public string USCourtBranch { get; set; }

        [JsonProperty("CaseTitle")]
        public string CaseTitle { get; set; }

        [JsonProperty("judgementIndexTables")]
        public JudgementIndexTables[][] JudgementIndexTables { get; set; }

        [JsonProperty("billing")]
        public Billing Billing { get; set; }

        [JsonProperty("sidebar")]
        public string Sidebar { get; set; }

        [JsonProperty("parsed")]
        public bool Parsed { get; set; }
    }

}
