// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class Notes
    {

        [JsonProperty("Office")]
        public string Office { get; set; }

        [JsonProperty("CaseFlags")]
        public string CaseFlags { get; set; }

        [JsonProperty("NOS")]
        public string NOS { get; set; }

        [JsonProperty("Cause")]
        public string Cause { get; set; }
    }

}
