// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class QueryResultShort
    {

        [JsonProperty("PartyName")]
        public string[] PartyName { get; set; }

        [JsonProperty("PartyType")]
        public string PartyType { get; set; }
    }

}
