// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class TransactionTable
    {

        [JsonProperty("DocNo")]
        public object DocNo { get; set; }

        [JsonProperty("EventName")]
        public object EventName { get; set; }

        [JsonProperty("EventFiled")]
        public string EventFiled { get; set; }

        [JsonProperty("EventTerminated")]
        public string EventTerminated { get; set; }
    }

}
