// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class WrittenOpinionsReport
    {

        [JsonProperty("CaseNumberName")]
        public object CaseNumberName { get; set; }

        [JsonProperty("DateFiled")]
        public string DateFiled { get; set; }

        [JsonProperty("Doc")]
        public Doc Doc { get; set; }

        [JsonProperty("Description")]
        public string Description { get; set; }

        [JsonProperty("Notes")]
        public Notes Notes { get; set; }
    }

}
