// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{

    public class CaseLookupPairs
    {

        [JsonProperty("cases")]
        public Case[] Cases { get; set; }

        [JsonProperty("parsed")]
        public bool Parsed { get; set; }
    }

}
