// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace USCourts.AO.Epa.Pacer
{
    public class Case
    {
        [JsonProperty("caseTitle")]
        public string CaseTitle { get; set; }

        [JsonProperty("caseId")]
        public string CaseId { get; set; }
    }

}
